---
title: "Joe Roe – CV"
author: Joe Roe
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['joeroe_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis', 
  echo = FALSE
)

library(magrittr) # For the pipe
source("joeroe_cv.R")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "data/",
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
if(params$pdf_mode){
  cat("View this CV online with links at _https://joeroe.io/cv_")
} else {
  cat("[<i class='fas fa-download'></i> Download a PDF of this CV](https://joeroe.io/cv/joeroe_cv.pdf)")
}
```

Contact {#contact}
--------------------------------------------------------------------------------

```{r contact}
CV %>% print_contact_info()
```


Programming {#skills}
--------------------------------------------------------------------------------

```{r skills}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with [pagedown](https://github.com/rstudio/pagedown) ([source](https://github.com/joeroe/joeroe.github.io/cv))  
Last updated `r Sys.Date()`



Main
================================================================================

Joe Roe {#title}
--------------------------------------------------------------------------------

```{r intro}
CV %<>% print_text_block("intro") 
```



Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r education}
CV %<>% print_section('education')
```



Academic appointments {data-icon=university}
--------------------------------------------------------------------------------

```{r academic_employment}
CV %<>% print_section('academic_employment')
```



Publications {data-icon=book .no-timeline}
--------------------------------------------------------------------------------

::: aside
```{r paper_aside}
CV %<>% print_text_block('paper_aside')
```
:::

```{=html}
<ul class="citations details">



<li>


Richter, T., Darabi, H., Alibaigi, S., Arranz-Otaegui, A., Bangsgaard, P., Khosravi, S., Maher, L., Mortensen, P., Pedersen, P., <b>Roe, J.</b>, &amp; Yeomans, L.,
2021.
<a href="/papers/2021/richter_et_al_communal_buildings.html">The formation of Early Neolithic Communities in the Central Zagros: an 11,500 year old communal structure at Asiab</a>. 



<cite>Oxford Journal of Archaeology</cite>, forthcoming.




</li>




<li>


Khosravi, S., Pedersen, P. N., Alibaigi, S., <b>Roe, J.</b>, Heidary Dastenaei, M., Miladi, B., Darabi, H., Richter, T., &amp; Mortensen, P.,
2020.
<a href="/papers/2020/khosravi_et_al_2020_razavar.html">Archaeological Landscape of Razavar Valley in the Neolithic Period: the survey of the 8th–6th millennium BC in the north of Kermanshah Province</a>. 


    [<span lang="fa">چشم‌انداز باستان‌شناختی درۀ رازآور در دورۀ نوسنگی: بررسی استقرارهای هزاره‌های هشتم تا ششم پ.م شمال استان کرمانشاه</span>]
    (in Persian).


<cite>Pazhoheshha-ye Bastan shenasi Iran</cite> .


<a href="https://doi.org/10.22084/NBSH.2020.21133.2094">doi:10.22084/NBSH.2020.21133.2094</a>

</li>

<li>


Martin, L., &amp; <b>Roe, J.</b>,
2020.
<a href="/papers/2020/martin_roe_2020.html">The Kheshiya Cattle Skull Ring: Zooarchaeological Analyses</a>. 



    In McCorriston, J., &amp; Harrower, M. J. (eds.), <cite>Landscape History of Hadramawt: The Roots of Agriculture in Southern Arabia (RASA) Project, 1998–2008</cite>, pp. 275–348.

Cotsen Institute of Archaeology Press.
<a href="https://doi.org/10.2307/j.ctvzgb8n3.20">doi:10.2307/j.ctvzgb8n3.20</a>

</li>

<li>


Nebbia, M., &amp; <b>Roe, J.</b>,
2020.
<a href="/papers/2020/nebbia_roe_2020.html">Landscape Studies</a>. 



    In Gaydarska, B. (eds.), <cite>Early Urbanism in Europe: The Trypillia Mega-Sites of the Ukrainian Forest-Steppe</cite>, pp. 60–107.

De Gruyter.
<a href="https://doi.org/10.1515/9783110664959-007">doi:10.1515/9783110664959-007</a>

</li>




<li>


Jones et al.,
2019.
<a href="/papers/2019/climate_change_in_southwest_asia.html">20,000 years of societal vulnerability and adaptation to climate change in southwest Asia</a>. 



<cite>WIREs Water</cite> 6(2): e1330.


<a href="https://doi.org/10.1002/wat2.1330">doi:10.1002/wat2.1330</a>

</li>

<li>


Henton, E., <b>Roe, J.</b>, Martin, L., Garrard, A., Boles, O., Lewis, J., Thirlwall, M., &amp; Jourdon, A-L.,
2019.
<a href="/papers/2019/henton_et_al_2019.html">Epipalaeolithic and Neolithic gazelle hunting in the Badia of north-east Jordan. Reconstruction of seasonal movements of herds by stable isotope and dental microwear analyses</a>. 



<cite>Levant</cite> 50(2): 127-172.


<a href="https://doi.org/10.1080/00758914.2019.1598764">doi:10.1080/00758914.2019.1598764</a>

</li>




<li>


Arranz Otaegui, A., González Carretero, L., <b>Roe, J.</b>, &amp; Richter, T.,
2018.
<a href="/papers/2018/founder_crops_vs_wild_plants.html">"Founder crops" v. wild plants: Assessing the plant-based diet of the last hunter-gatherers in southwest Asia</a>. 



<cite>Quaternary Science Reviews</cite> 186: 263–283.


<a href="https://doi.org/10.1016/j.quascirev.2018.02.011">doi:10.1016/j.quascirev.2018.02.011</a>

</li>




<li>


Martin, L., Edwards, Y., <b>Roe, J.</b>, &amp; Garrard, A.,
2016.
<a href="/papers/2016/faunal_turnover_in_the_azraq_basin.html">Faunal turnover in the Azraq Basin, eastern Jordan 28,000 to 9,000 cal BP, signalling climate change and human impact</a>. 



<cite>Quaternary Research</cite> 86(2): 200–219.


<a href="https://doi.org/10.1016/j.yqres.2016.07.001">doi:10.1016/j.yqres.2016.07.001</a>

</li>

<li>


<b>Roe, J.</b>,
2016.
<a href="/papers/2016/pia_at_25.html">PIA at 25: A Retrospective</a>. 



<cite>Papers from the Institute of Archaeology</cite> 25(2): p.Art. 16.


<a href="https://doi.org/10.5334/pia.517">doi:10.5334/pia.517</a>

</li>




<li>


Allentuck, A., Martin, L., &amp; <b>Roe, J.</b>,
2015.
<a href="/papers/2015/refuse_disposal_in_the_early_epipalaeolithic.html">Refuse Disposal in the Early Epipalaeolithic? Preliminary Zooarchaeological Evidence from Kharaneh IV, Eastern Jordan</a>. 



<cite>Bulletin of the Council for British Research in the Levant</cite> 10: 67–69.


<a href="https://doi.org/10.1179/1752726015Z.00000000034">doi:10.1179/1752726015Z.00000000034</a>

</li>




<li>


<b>Roe, J.</b>,
2014.
<a href="/papers/2014/review_of_green_arabia.html">Review of *Green Arabia*: Human Prehistory at the Crossroads of Continents</a>. 



<cite>Papers from the Institute of Archaeology</cite> 24(1).


<a href="https://doi.org/10.5334/pia.458">doi:10.5334/pia.458</a>

</li>


</ul>
```



Conference presentations {data-icon=chalkboard .list-only .break-before}
--------------------------------------------------------------------------------

::: aside
```{r talk_aside}
CV %<>% print_text_block('talk_aside')
```
:::

```{r talk}
print_talks_from_md(c("talks", "posters"), "../")
```


Software & datasets {data-icon=cube}
--------------------------------------------------------------------------------

::: aside
```{r software_aside}
CV %<>% print_text_block('software_aside')
```
:::

```{r software}
print_software_from_md(c("code", "datasets"), "../")
```



Field projects {data-icon=map-marked}
--------------------------------------------------------------------------------

::: aside
```{r field_aside}
CV %<>% print_text_block('field_aside')
```
:::

```{r field}
CV %<>% print_section('field')
```



Grants & scholarships {data-icon=money-check-alt .break-after}
--------------------------------------------------------------------------------

```{r grant}
CV %<>% print_section('grant')
```



Teaching & public engagement {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

::: aside
```{r teaching_aside}
CV %<>% print_text_block('teaching_aside')
```
:::

```{r teaching}
CV %<>% print_section('teaching')
```



Professional service {data-icon=users}
--------------------------------------------------------------------------------

::: aside
```{r service_aside}
CV %<>% print_text_block('service_aside')
```
:::

```{r service}
CV %<>% print_section('service')
```



Professional memberships {data-icon=bookmark}
--------------------------------------------------------------------------------

::: aside
```{r member_aside}
CV %<>% print_text_block('member_aside')
```
:::

```{r member}
CV %<>% print_section('member')
```



Workshop & seminar participation {data-icon=comment-alt}
--------------------------------------------------------------------------------

```{r workshop}
CV %<>% print_section('workshop')
```



Other employment & volunteering {data-icon=briefcase}
--------------------------------------------------------------------------------

::: aside
```{r other_aside}
CV %<>% print_text_block('other_aside')
```
:::

```{r other_employment}
CV %<>% print_section('other_employment')
```



```{r}
CV %<>% print_links()
```